// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tollroad/user_vault.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserVault struct {
	Owner             string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	RoadOperatorIndex string `protobuf:"bytes,2,opt,name=roadOperatorIndex,proto3" json:"roadOperatorIndex,omitempty"`
	Token             string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Balance           uint64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *UserVault) Reset()         { *m = UserVault{} }
func (m *UserVault) String() string { return proto.CompactTextString(m) }
func (*UserVault) ProtoMessage()    {}
func (*UserVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e24867a4d20a632, []int{0}
}
func (m *UserVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVault.Merge(m, src)
}
func (m *UserVault) XXX_Size() int {
	return m.Size()
}
func (m *UserVault) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVault.DiscardUnknown(m)
}

var xxx_messageInfo_UserVault proto.InternalMessageInfo

func (m *UserVault) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UserVault) GetRoadOperatorIndex() string {
	if m != nil {
		return m.RoadOperatorIndex
	}
	return ""
}

func (m *UserVault) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserVault) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*UserVault)(nil), "b9lab.tollroad.tollroad.UserVault")
}

func init() { proto.RegisterFile("tollroad/user_vault.proto", fileDescriptor_9e24867a4d20a632) }

var fileDescriptor_9e24867a4d20a632 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xc9, 0xcf, 0xc9,
	0x29, 0xca, 0x4f, 0x4c, 0xd1, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x2f, 0x4b, 0x2c, 0xcd, 0x29, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0xb2, 0xcc, 0x49, 0x4c, 0xd2, 0x83, 0x29, 0x80,
	0x33, 0x94, 0xea, 0xb9, 0x38, 0x43, 0x8b, 0x53, 0x8b, 0xc2, 0x40, 0x6a, 0x85, 0x44, 0xb8, 0x58,
	0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x1d,
	0x2e, 0x41, 0x90, 0x52, 0xff, 0x82, 0xd4, 0xa2, 0xc4, 0x92, 0xfc, 0x22, 0xcf, 0xbc, 0x94, 0xd4,
	0x0a, 0x09, 0x26, 0xb0, 0x0a, 0x4c, 0x09, 0x90, 0x19, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0xcc,
	0x10, 0x33, 0xc0, 0x1c, 0x21, 0x09, 0x2e, 0xf6, 0xa4, 0xc4, 0x9c, 0xc4, 0xbc, 0xe4, 0x54, 0x09,
	0x16, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x18, 0xd7, 0xc9, 0xf5, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f,
	0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b,
	0x8f, 0xe5, 0x18, 0xa2, 0xb4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0xc1, 0xce, 0xd7, 0x07, 0xb9, 0x5a, 0x17, 0xec, 0xc1, 0x0a, 0x7d, 0xb8, 0x5f, 0x4b, 0x2a, 0x0b,
	0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xfe, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xce, 0x41, 0xba,
	0x77, 0x04, 0x01, 0x00, 0x00,
}

func (m *UserVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Balance != 0 {
		i = encodeVarintUserVault(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintUserVault(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoadOperatorIndex) > 0 {
		i -= len(m.RoadOperatorIndex)
		copy(dAtA[i:], m.RoadOperatorIndex)
		i = encodeVarintUserVault(dAtA, i, uint64(len(m.RoadOperatorIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintUserVault(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUserVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovUserVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovUserVault(uint64(l))
	}
	l = len(m.RoadOperatorIndex)
	if l > 0 {
		n += 1 + l + sovUserVault(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovUserVault(uint64(l))
	}
	if m.Balance != 0 {
		n += 1 + sovUserVault(uint64(m.Balance))
	}
	return n
}

func sovUserVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUserVault(x uint64) (n int) {
	return sovUserVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUserVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserVault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserVault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoadOperatorIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoadOperatorIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUserVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUserVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUserVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUserVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUserVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUserVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUserVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUserVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUserVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUserVault = fmt.Errorf("proto: unexpected end of group")
)
